
Ready
Atleast here
[38m[48m[mp3 @ 0x55930bb585c0] Estimating duration from bitrate, this may be inaccurate
Ignoring exception in command gen:
Traceback (most recent call last):
  File "/home/lua/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/lua/Documents/Code/gpt3-bot/main.py", line 158, in gen
    await ResetAudio(ctx)
  File "/home/lua/Documents/Code/gpt3-bot/main.py", line 147, in ResetAudio
    channel = author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/lua/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/lua/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/lua/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'channel'
Atleast here
Atleast here
[38m[48m[mp3 @ 0x5571837d15c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
[38m[48m[mp3 @ 0x55957b5225c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
[38m[48m[mp3 @ 0x561be834c5c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
[38m[48m[mp3 @ 0x56062aeb25c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
[38m[48m[mp3 @ 0x55e5d30d15c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
[38m[48m[mp3 @ 0x562a879b75c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
[38m[48m[mp3 @ 0x559b4ad525c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
[38m[48m[mp3 @ 0x55a4c3bc55c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
[38m[48m[mp3 @ 0x56192ff5e5c0] Estimating duration from bitrate, this may be inaccurate
Atleast here
Ignoring exception in command gen:
Traceback (most recent call last):
  File "/home/lua/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/lua/Documents/Code/gpt3-bot/main.py", line 158, in gen
    await ResetAudio(ctx)
  File "/home/lua/Documents/Code/gpt3-bot/main.py", line 147, in ResetAudio
    channel = author.voice.channel
AttributeError: 'NoneType' object has no attribute 'channel'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/lua/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/lua/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/lua/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'channel'